import { StyleSheet } from "react-native";
// our styles for the project


export const styles = StyleSheet.create({
    scrollContainer: {
        flexGrow: 1,
        paddingBottom: 120,
        backgroundColor: "#F8FBFA",
    },
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "flex-start",
        paddingTop: 10,
        backgroundColor: "#F8FBFA",
    },
    inputView: {
        width: '100%',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    logo: {
        width: 120,
        height: 120,
        resizeMode: 'contain',
        marginBottom: 20,
    },
    section: {
        alignSelf: "stretch",
        marginLeft: 20,
        marginBottom: 5,
        marginTop: 5,
    },
    sectionIons: {
        alignSelf: "stretch",
        marginLeft: 20,
        marginBottom: 20,
        marginTop: 15,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#52946B",
        marginBottom: 10,
    },
    input: {
        height: 40,
        backgroundColor: "#EAF2EC",
        borderWidth: 0,
        paddingHorizontal: 10,
        color: "#52946B",
        width: "90%",
        borderRadius: 5,
        margin: 10,
    },
    showimage: {
        width: 100,
        height: 100,
        borderRadius: 5,
        marginRight: 10,
    },
    cameraimage: {
        width: 250,
        height: 250,
        borderRadius: 5,
        marginRight: 10,
    },
    itemboxrow: {
        flexDirection: "row",
        alignItems: "center",
        marginRight: 8,
    },
    itembox: {
        alignItems: "center",
        marginRight: 8,
    },
    itemTitle: {
        fontSize: 13,
        fontWeight: "bold",
        color: "#0D1A12",
    },
    itemCategory: {
        fontSize: 13,
        color: "#52946B",
        marginLeft: 0,
    },
    categoryButton: {
        width: 100,
        height: 50,
        borderRadius: 8,
        marginRight: 6,
        marginTop: 5,
        marginBottom: 5,
        marginLeft: 2,

        // iOS shadow
        shadowColor: "#000",
        shadowOffset: { width: 1, height:2 },
        shadowOpacity: 0.25,
        shadowRadius: 0,

        // Android shadow
        elevation: 6,
    },
    categoryContent: {
        height: 50,
        paddingVertical: 0,
        alignItems: "center",
        justifyContent: "center",
    },
    categoryContentWide: {
        height: 50,
        width: "100%",
        paddingVertical: 0,
        alignItems: "center",
        justifyContent: "center",
    },
    categoryLabel: {
        fontSize: 13,
        fontWeight: 'bold',
        lineHeight: 18,
        // color: "#0D1A12",
    },

    inputdescription: {
        height: 120,
        backgroundColor: '#EAF2EC',
        borderWidth: 0,
        paddingHorizontal: 10,
        color: '#52946B', // Text color
        width: '90%',
        justifyContent: 'space-around',
        margin: 10,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
        textAlignVertical: 'top',
    },
    cameraviewadditem: {
        backgroundColor: '#F8FBFA',
        borderWidth: 1,
        borderStyle: 'dashed',
        width: '60%',
        height: '35%',
        color: '#0D1A12',
        borderColor: '#52946B',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    scrollContaineradditem: {
        flexGrow: 1,
        justifyContent: 'flex-start',
        paddingHorizontal: 12,
        paddingBottom: 250,
        backgroundColor: '#F8FBFA',
    },
    loginregisterbutton: {
        backgroundColor: '#EAF2EC',
        color: '#0D1A12',
        fontWeight: 'bold',
        padding: 12,
        margin: 7,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
    },
    camerabutton: {
        backgroundColor: '#EAF2EC',
        color: '#0D1A12',
        fontWeight: 'bold',
    },
    camerabuttontext: {
        backgroundColor: '#EAF2EC',
        color: '#0D1A12',
        fontWeight: 'bold',
        padding: 10,
        margin: 0,

    },
    gridContainer: {
        padding: 10,
        justifyContent: 'center',
    },
    innerContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
        width: '100%',
        maxWidth: 500,
        paddingTop: 0,
    },
    camerabuttontext: {
        backgroundColor: '#EAF2EC',
        color: '#52946B',
        fontWeight: 'bold',
        padding: 5,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
    },
    inputLocation: {
        height: 40,
        backgroundColor: '#EAF2EC',
        borderWidth: 0,
        paddingHorizontal: 10,
        color: '#52946B', // Text color
        width: '80%',
        justifyContent: 'space-around',
        margin: 0,
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
    },
    tomarketbutton: {
        backgroundColor: 'lightgreen',
        color: 'white',
        fontWeight: 'bold',
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 5,
    },
});

export default styles;
